AWSTemplateFormatVersion: '2010-09-09'
Description: Security Groups for ALB and EC2

Resources:
  ALBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB SG
      VpcId: !ImportValue VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Private SG
      VpcId: !ImportValue VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSG

Outputs:
  ALBSG:
    Value: !Ref ALBSG
    Export:
      Name: ALBSG

  EC2SG:
    Value: !Ref EC2SG
    Export:
      Name: EC2SG
