AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Private Instance with Nginx and SSM

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0db3df45b0b0720bc # Latest Amazon Linux 2023 AMI in ap-southeast-1
      SubnetId: !ImportValue PrivateSubnetId
      SecurityGroupIds:
        - !ImportValue EC2SG
      IamInstanceProfile: !ImportValue EC2InstanceProfile
      EbsOptimized: true
      Monitoring: true
      Tags:
        - Key: Name
          Value: johan-testcf
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 50
            VolumeType: gp3
            DeleteOnTermination: true

  AttachToTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroupAttachment
    Properties:
      TargetGroupArn: !ImportValue TargetGroupArn
      TargetId: !Ref EC2Instance
      Port: 80
